server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pedidodb
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

pedido:
  api:
    url: http://external-api/pedidos